name: insta_food
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.0.3
  flutter_loggy_dio: ^3.0.1
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^3.0.3
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  

dev_dependencies: 
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

